version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: bot_database
    networks:
      - embassy_bot_network
    volumes:
      - postgres_data_database:/var/lib/postgresql/data/
    env_file:
      - ${PWD}/.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT_EXPOSE}:${DATABASE_PORT}
    expose:
      - ${DATABASE_PORT_EXPOSE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: -p ${DATABASE_PORT}

volumes:
  postgres_data_database:
